### ISSUE TITLE
Требуется версия Хромдрайвера, которого нет, для хром 116.0.5845.141. Подскажите как быть?

### ISSUE THREAD

**Issue by AndresKorvin** [AndresKorvin/allure#1]
# Описание
Требуется версия Хромдрайвера, которого нет.
# Шаги воспроизведения
1. Запустить app-card-delivery.jar
2. Запустить DeliveryTest
3. Прочесть лог, фрагмент ниже

Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 28742
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.141 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 

# Окружение
* **Операционная система** Windows 10 Домашняя для одного языка 21H2
* **Браузер** Google Chrome Версия 116.0.5845.141 (Официальная сборка), (64 бит)

**Comment by andrew-pahomov** [comment]
Обновите селенид до версии 6.17.2
